version: '3'
services:
    app:
        build:
            context: .
        environment:
            - NODE_ENV=test
            - NODE_CONFIG_ENV=test.integration
        volumes:
            - .:/app:rw
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        command: mongod --smallfiles --logpath=/dev/null