image: andrewzzz/aws-lambda-nodejs:4382145e33052602f085a9548dc42d5979156673

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build
          - npm run test:ci
          - npm run test:lint
          - npm run test:sonar
        services: 
          - mongo
    - step:
        name: Deploy beta version
        trigger: manual
        caches:
          - node
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build
          - npm publish --tag beta
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            - npm install
            - npm run build
            - npm run test:ci
            - npm run test:lint
            - npm run test:sonar
            - npm publish
          services: 
            - mongo
definitions:
  services: 
    mongo:
      image: mongo
