language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: Sz4EuswJdTDYWbaMhF31lwJ6tYeCcbdsXKc510vVpF58BEwxddepwef5JWZRJGio0wpm4zVCrAfvuhEUt/MDNUxGR62dj5m3cFlXMG2kzi7VF+Kq7FsvH1LPgGZODwD7YEi0D9DPEzIujp3Z2WR71D1p2VqRXZRwTKB660Bip4ojNX7iB3quIqWKphXhg3F5mzY8UREJpSrelOdDrqyomWdpcKcjiTHMjTnqVJ3ICVszxBf8d8Mlq0najZHGrhV7/K2gg3xGgW2He80UuC+3XWN0FxQ7ffnGMrk8P3NSQ0RSzS2E/ZAgELaVfHQbpCEdxXDy95zCIpaLpKXr2MiVJ/IHEoKCUpoau4Y5Q6BTp7tgyqHT1HZsCR9nniq0zsMxHj4ayoz1X7RqPE4r8KR+PFH7RKGuiY4y4cGH2FQ3YxsE6GH6zM0qYkpnHW+T33zn0BxiCFHGud96SHDoYvjT0fJxS0TG+NeRNBnnPPTQ5knhuQXb2NwaE6DCXhFVOUA4EzvgZvTJ8hO/+Aj7yhSNdg/Zx11JPGXuVXL/gPyj1vXAhJdck/l3ECk0tabwCh7swYfg14TPzCaB2lZ2+5PfoxunCH8lLOEkHsybX5bQ+xBw9HZEKhrmlStkulkVdlExAyxxF9MRenCZSR7iVpX9w818biMYAGchGU1ISvMbrSo=
  - secure: vHHQQSG3fX1+/XyOefrf/AFFg0/pEItgSnOm7X6YB+y5CobrsVZ+9MRra/SE5mQuQQW6vLlzmmEyjnJHZCeVqC8OWbOpg+hhRG9IVUMrvmhFbR/6U83JSXW47Dt/MkeH/lUL7kfbpCGBwm2yxDPVXOyy3bV7UOlN/VhudHGsns5u6JBl7ia3qNMHGOQzNmmEx3QxiW/Un06s9ra6P/AhqEwzqi7AVcn4AhnFfF2QfjbkqT2jVwPMP0PkdSQ6JCvP3FlLwIUdAdNBlRjww6Zyr0XiX+rCQ8Pmne/ozxPf799m5SeF2Gw5Ec5lkcIcNGOa2Rs210ukz2KB+nKZ9lP0JoIidm4YtFQY2XbaSDdPRXVvzAuencrqH4T3PEgaIfp1ZH6tpmKjnubqs56eeINKllrfSekf5JibHhWhjMvMk4hymZxLLTREwpsji3iYaS+GxWGvxu8CisE5PoG9tQJFweI0V1L1LzSEL1+i6/hf+kVkf7d5ZnK+6aevjZz8Y1Z+/Xnso9a1E7x9wH9DSwinpFERhtUoACmInge9sVsjkJ2KpcCqzeDDtk9GzbdAY7LpbvZ+IcYigtCwOBs0aUGwNLZQ8ANHmouiGXX6Omqp9U0nO73yukDCQLhJTTuA2SoH/Sc5FUJTsRIwpDKE8zgPNSWuz9L3wHytAMRPhNoTJSs=
  - secure: Gw2XawIRJdyZqRmDp5J374IC9Vl6QYlcUo+mU+HKCm/KvmsaAzBhoEDz4DK+ZEctR1nEiSOMah8BjmVs/nlPl/xCGhSLvIuuf+CEAzYGlWr6HNfn944WmpXpYQdGXXeAO24K+dV5kalrm8JWQlgHSxUont9eNxmdPmXmu5x7SFwOAMh/lt1B9p2lsq1ycDsxEuDMsvRSj8rCPxV5gL6GuhQzKw4zL4qFiNF7UhnRHrF6ShfqgGH2cvtGxKELGV4fY0kkgPkiZ7QmIFAchHTxR6NDIDBXc2wNryd80adtQPg9qojjH02oEhGdap55RtiDQ8o0mZPhwde/vV6QZ78cVN1DULs02+IK6K31WJYAyQytdhfmR9EDZ/9T7Voyu/FmTrAnANuXv6NZZhfYKUjeBk/eE+Q8fHE5P+7AVuKuK34XHOXnIqGfyu+ehSBkhfG7vKoeb6TyBpWTxssuMGf8UZPtM7sLTbdjStnD7ZD6v9Sj8m8w+F6PGldsejBkOBR3KI1avrDJYUqoH6ym7eoTKVuZRMsb8Iu52GF315bO9Gb1hK8f6bShwcSg+9+6vULTOlilCfNraDngM+vursqolRe+aQqYNjl27aToLD4hlU0dg/BSk7nzFVo/ntdQxh4Ebuo6i+3fU3WOkVcPcFUwSiUdt6DOnt3j7oEK4lu2Gwg=
  - secure: WGeZ6Q8zxBvEi82otDiI3RZ72OHQrG0hqxYSOYgUX6FDZeYMaE8GvdudCWQFJe+phGY73MgstVPriV9sveyhXfTR0TizhZAj4t6TWf0V+UTbd/KEIicFlQz1C4xGz27ORhRClDrWJbSjloLbHyIQL6ivciCne5/DyMuVokUN5vGNoBu3/mPS7cc9BgMDXBwdWBjAPrWZnH9CscWu7zg646YZeodtWXr/2/Mu0NY7r23XXypicRFwvwgNVxpCm32MZd8s0J3AhkAkRp9abbqfOda1dqYq7tesCdE568YVE4IcK0WEaKXNPSTTqudbnv4bL/cvdvQdu2qK6cPShutlH+cfD8V2NrD4oZ3E9bpjayJhYFYrJU2YVcCz6xcrahD7MfAaN7AYo0ZiC3BJKvrPovXrsD+HnGp1vgxNSFPUaFdpDh+QjUdGaimdwsaCxoEUM2sE3ciaxG64M13BV43m2+55cmYbvhnQpQSF6MfsnU+WittE3GB/pVAlSUN02pAxOWiohD4vXM8y0hBfbYF5gu/veYAmpyoVtHw1tVIP2qwf0/GSO0vcJiYmD8Y4tuGLEM33RiuugT2o5q+DI0b0522RxDXpwhgo/NCRsq55+3JW3eXVY+ljaLUsA7bMlKFj7FallJU8TwZ9/7FgPdItP9F9J1sbEzaw5rh0zuCoJTM=
