language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: zGBlaScRfC+sjXjMb1ZtjfY/XiT5GfUwoGaRnO3zqbmwkrfxxfU3PTTOmR8rgVNS6EMRtaZ/zp8FZu++mPIvmXD2ysLNwnBNwdiaGpZq7MsRKljNHmBtToSESZporYfq1BTQVOgPkPJK1rapePVDnCYnr7rO3vWCBdkwYbFA/aZLcGqlgrPlQE7lbFAPym3J7BythCA9kpcrNFe7Qb7ijoRyRqsCxTNvtprQfDEHHvaIwDTI+c8Im1R0KqGCKfI/XGWkOwFRjErSiG6WTQFqGEyC3SKK+nTvgKyOgHKK5XmaQGKBQFLcfGGYYWyi1xK6CPG9btv2B3bKXIBi5PcBK7zTWB3SaalH94LnhQLtk1eIePR8SfB46gJo7PFaYYsrcrID391Q3rTQV73YoDGp1YMwsn4yh0fY2gMxIWu+uicP7x7VnGNZA/RWSBTi33hCIxArTOdGIVFzK0MkIcgFPJAiXoPwA7E5xORLRfF9Xmjp0FbxNwiqR5izqiEJl9hJEibLvsvuJfrX7IToYFJqGeQ3JTvdm16s/k1sA/757mzPkJQlQXZZCyBJGEsCRQZbuoADC5E/CzOtYKEAw82JVRUwmHfImxrk6fTzOlmKkAIw8mXZ7MciPe9PqXKfVbOr93iyhr+AqfcQsJMN9L/8GCuWgr7qsqSlZTSUaVt7rGM=
  - secure: uchudV4Y9+nU4+hbJxIwcVZDzO/e0dbc8srwS8/Woh8rPQNZlLOwxFmYh61lu+faG4LYkMaOO4zw1Hys/Z7xO2OWui9ngA+0vAyOq2SdvgOw7OW13U4U2z3KBpoapm9fAizCRtIzpNbWK2W1Q/mKu0Jg4etGF4oJ1nZW5aUvWmBiESiEQj8+w79XOboOIr7v2kRoqlohGjnxTfOEE7k7vecIbX71CkhUs5sNuuWoGje4XeTJTYPAmuT9CXtGIJp8RV1WFlwyII9Og4vlplObVUe476iUcKJWSg/cUGaqc+bd6oA7YOEXTr7IMqh0DmceMh67Nrx09mJQeAwbRbN8E+M1h/31Jl8fn6je2m2vwvHSG9ttVuJSMJ7kAG5o14wGRHqBh2IWGjzBqkzans30ioTRFvdiI++Yi1o40BhknRpPKljpR/rM7o1DVWF2fdtVa65/2s2HNbso0fMAjvdyvatFfdiisoW8lTRytdkVZYlD7N+ocUgNKeuCAaazbs2lcn1iaYIf7cjkUNGBlsvwKTye3yIoQXAQrQDVEhremFbcnzO9Ngr482EdZ3uxKYiXnPw6y2eOO5uLkQ7rR8QEm3t3/L5DaalghvzBzpMAwstH6i570Ppsh2Jh1MTV5AIAhdRr1toH4IwOgymKg65CG9R6JkA+GPlW2amWsaJtMWs=
  - secure: zp3JVjcGe2b3Q00i8wNrD0jJoAEszT+xQ7FxPcgXCFMViU2VcqtbL9O8H46AuQZPObc9dKYsq6XufSSFjONYhFKHqQZlU9xasy+qspheuFvcngXZV5v+LzVhxKHAuMm3gldkfreakaY5L1gE9hbg4JEMfb9/zhqaNTc48hOaXoO7pvYBf9JHbqmQsiwKzuSN0xY+EtWS3MQqLa+/oeClrAgALA25FTWjYqULjA3hkoNMUHSRXti6UF8XIFdEP1dkBSHzsFgsZcdC8dS2xuNEYLuSGfMeexbKyc1hXP7HURVkJlmzQixR3BEqyu6CwGAatmu1NF8Ecvtpg0Yb7yWGo5N52oj0hJeDIdNoMoXjZ+88weNscG7xe445tWmepuO5Sd+ljlvgv9dA/FVVUk9Bk1HBNeRwBPJ5lv0ayeebLhW7IybV1x+H+80k5Ie338+54UqVsn+Xag3d42sd29GASkzEhnHPIHnHl5ac0X7rvLyuyZAvF7vY//MMUmDuXeQuugSxSeMRdJcv2MjBFfcPMEIZq+u7uHS/8KwL9PAtC6JIwSiRDBs2f4ykgJ7kXwIT3IDT6LmDnshdqLRoeqMYNBR0f4P6Rum1LLBWWeP5YgQja2xkMTMyfDDiHnkB43DBPNc7MUgQCN5sJj2Afvw0XP+nFkO/U7a6ekPHY8XQsZI=
