language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: RIJ81A4pJZKZOz3X7tTNy2ZYm8KY8gvyv44mxoUqp4P4BW3PxN0xLTmyLbL/m7/SMrAB8MdcMHpHrNTvJq4OggyorHohZndbFmWUl4LWQu1pQj7OOpIjEcmNqpX67YhG7+vnmN2GvPkC99nbXjy8SDPhPNntgLWt1/mxGLBqt75/04aYGg5qQ919gIYghgrWJ1icvJfuXC3iZ+L36FIM2HfoNNuw7crzBdEDJswj0Svrjw8Zup72pPX63dH8YBF8bMz8ILAkXdEn5hcb2iL7hERxzAxoh2Hxkhtlk5PZie/JxQCbQDdJLotXVAQ7t4TU4uq0aJWNPiDF1MlDDWcPSoVfFQ8K+cIjvMSbPKrb1v2LIQpfAnPkZZ1h7Zajn0+/8Z13bpoAsX1tm9MvSDTB4wn6EiRYX455PAGqvy1PghcANWX3eJoSlyExeYStK7REDqI0f1GyFP+DVUzay0DSOcxaZ1VunQsGKco7r1l45FLE+u7Q1T+qSkbRrBEJ5j2OgA9HuvpPbQ1Xoy/3h232T63ViPCgS4szWYUheXqztGwVoI57HBP2d7dU1E08YnwcikCY4ouXWHnc3YXold328I3IKNvCwCmm4nOZOKB76rfYIyL3PVQvgzic9Mkz/Y1lRjm8z+gQJiNyXwrJPcr6Ol3+l8XmBePg/Q+xK46+95g=
  - secure: BrQE8XRsBq/KNeUBjLuWy2Bdd/EXw84e4sxKftfFmrjQmXWgLBZxtcpLVJk9e7cTW1eCMzslb0pPbjr3kzrqKVyiqfVLnZIdNQdsh1PLDzUdUh81v1kejQY4ueEej2U2FcDDak/pKPlsO8aGt9CB2kjBGCzQEXk9vk+wkTQTByu7jdVQ/jg8N1b+ViQLAs8oG1eEIUoO8VXUptpKu7Txabi3W32NFe5OhLSsgBP89WrDy17cR8bFtmWWA/arJSYvZqIbZTblPgM8hwkzK0CJSVeXY0RdR+n7XU410wGPL2uxxjHVZ84jVlqzegN75/P5grTtEAXHj/QOVuOI+b2lWh/R0JfVR14jEir7DYq71X1O24+TL+58dEvsvMY0r3XE2vUFuUL1fvJWWXvw/9K+902DvZhzrfbRWU1YHLaWo4bHJFgNwIlhK4GgDl3A0Y31myAbqqCfxZdaAlzMkiEX/Sl12Ox5vki4HdYQt573c/59ck+Pcw3gtEQBbTdVv4aqf1BQ2BGdw8CvTH3mUEi31AbCmdlBVyLELYbVDG0F0Nhg9U7OUERkRw7M0dXtw3P27yoHNvnhvO7C+hhbyZRCAtAoNA62GTMqbu6Hd/K9gJSHozYT6CNHWuP0u4q1k7i72iC/HQNkRoFav5IYtU5ZZ6gW6FQk1gbynAgjyFy5SO4=
  - secure: SxLmtzj76vbXwYd4D6jhfR8mxiS47KqhcXDSt+isFzRDfw9pFoNIXm7R7Ywi6aJVrYGu7aJDgSOFsvlEkCUSMNP0H2R870s3vWGrkGw9zmDhossLHmjmiUmU6LeaAGSN+cOC/KX1t8exrkkIHCT1hI/MrcEooynKJd0niL4cdnsb5Vpit0U/jCKZlPX/gU7YvcoNmQUh8JUpDcv4qUaEUxrLnl7zmbqrnbcYCmWGZZA9ECoa5m+5mCBnpiBNluscbKK1YyeYg2liSvM6KnPA1tRUUp5Br7vIjPYsbGMxmlYesOQxz0nbSfbg9gmWJuH67de/h6iUXEqglJu5VVR0vczslRP4y3OeFmGHtOqsTAFTeLw3rAZmOAsMXrxxqHWxwpK5bAduKftyTxNArwHAFCPMBw0MaftqZIZ6N0/k73HIp3WUQFxdKyMsqdoDclNRy1MZmeQy68RBLGsBh1y8mWPUIGIrisGYhT9xbm3Xc0SZbLO3oxjcYH3eIF/Hq2Mppl2O4wJ3P2riwK8Sba6qBG6d81VALZEAoqBeFJRu1o2PS5EQutF+7WL4mb6X6Rjb2gnPsGJVaEkCSkjyZFr8Xx4yJVbsx3VBthC29wA2Hd6gzzRAyNUSjfis6UlfRft9/QUZWDw+K5iVugTVz6G0ae4DNGP7ZZCzxAdYaf7IFqc=
  - secure: OB4rtogrkvZUO0zPIQjtlOgG74GOPhT5bPMjp/YMR2cfwpKGoe4umdZTCBXhbFgcF2aGrmJX4zz63VLB/YYoIJfsMpVlmGAopOWisWzFuXk+FovUvaVeMOggPt2ZcFU9tAU3dhGRYaEW8zfLr0kyEI1bM2VEGtdrbKvH4QfFfRMhPG+kWnznrD0MfDZ6/dqd/Xg5vFE22puBxq4QKS56lXqPrnwCLoR6hwfWQOSJMyaleYLv1Jy3XFizBCUpBUiO1nVYtSRmOQLNHesvB2r924DW8nqjeINGZwXQrp2UUmy7BDCjoVKNGGdZhCj5ozK221EB+nsRGHCuFlGTTAc+MobsMiKRFuW5zbGljLznx1Zk0FLBmMetgQmqY65iRbw66UdjMmvRXqaCO6XLudfrbxLkVgMZQlc3MZpYhBpY7dqsl7XZdtQI3sRUwzhmZLePn78pUd7AmwKSwSc7IuUmCRcTmoVK6Fr1HKFf6EUoG7P6Gl4+Z31aDmfWQHe9uFZtIZGajxCnwPCPbrYSJWgb+bMjxsCLBwLqoDuggZsrIGRpCuqf0TpCk2L8SWCBm4SOHQws8Rynw9DOH9HE1E+hp/z2Jdf8t350UzOjJBSdrH5HY69SSxV599ZbBpvlkEnp/MTu72IdKk7I0znripUZR57edVXOpFekYL39jpL0pwk=
