language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: MUG1+hllK7ovb/9EyzzzSTsVqfUwUPyGrs/NMBqCyyBWzK+zLGMtTqqeV5urjBYNtRhaojGvc4f5SXe7n6PCt3bD1WL1V5fRwQrNkX3KjCj+lRsVqXlvdWlOHOdb6FdYcuYKoyutDtksUUSuzh1Ia+6xjcFgr6Su6NlQEv3H6P63KkpFr72N7HM4jqhOUmTeRxzEvwmYRtHrntzixyKQg6LhzSkqOWaQNq4Qo54WwDSBtVAcoe3YeRxz6pgZI5YGSR3qt809K9QOflVI2+KTReNkRAb6AwXdwWAu0NbNNTr+ONX+oaGpAV7uvSN8+F7W7/47AbZJXHDF2csVgiAT/XZ4yTwLdxcIOH6U11av4us2vDMeLYPZsnjdQx70q0aMJhqyjUI9BrX9S6ObgA3hF7tcPGuZm1azZGzhj+k1/sMkv2GfAxB+SZmFkMvDGCvBkcDyDA7cVeIzjHFyPQmkm/ff2DKULRXEqRjCSGEG2aHbl4JVDnnWVL6BWPPjtDws1yESg+rcskr/ADZOnWs+U3ybobfXNjqr5OC4a22oWd31roCIa8VL2KzBeaHQ+O8RvUW1JhwgiSx7oeisxyM/PyJvHtd1HOjq18eHRhFdPveT5myeKuraYiO4egy+cK2eO1EZYGQiXa3d7Ty9bOTKwbg11nKVi/o7Rk8pCekO3uU=
  - secure: dftXaF8J8taWEC6mL0aDtdG/CclLAUY+YB/ACFio9HSLRaCzDaMXQIFfU60nPHz6YK5nKWH7+UsGoF8Shw7GexxSdB9Scrz5vAX0MHims52v5/KNySTpaciE04U2Ba/8Rvc88Nh1tay9ueK3GBsK57kxROb1KRBwXnGFea7gvAbGIC5s+E4snRaxlDGcz3D3pL5zady1l4fjB5cWGz3Tpp4dsWYkiucHo3vff9i5YAxOq0XA3kkyca8+RCE/j70jqYL0ppt3NZzXf+jXquPMHF+GmZSe10zj5/vBfmgIsIJ+bs1aUFKSIOPRkt+l/D074d7RSoY68Bjrnv8vLWYUzstgnMAZwiKUr9+eRHkArHdSflyPATJaYmYJrg/D6xY0XP/7hS/RP2iUmZgoHW/EnG7OHKWOUfpN8y5C4Nimt3WHR9L0kuuJ5Lv59ETBX5xRff85wH6DcrDKBSQdZgTI9oobM/KhbG4KnFoU1ACt0vpPErmuJDG5jcexAHM7bTvnFwWcP8pHIvoefICg7I4eYUKUMtIin1vOKFG6rT1WHwrdJWCNS7kPfN5w5y7QyB1VOaqrCiACBYDVbnV6/wUA4ytoM0LBwLquljqe0KzUhomLWjwcsGdo36Ba2Bjye8InQfW5MWPfPcJV6JF4a2mGUy/I6RF4+ox2pCtFqQFWCN0=
  - secure: Dmg/8+N+sTJV2HuyLb1R5Kls/gvlmyQkpvkC5xElR2VsTnkC2VREZv/RcmelywxK0ctkSl+bDJzgzkB6WmYqcy4JtYD/zZ1k9aEriAstMDQ3mtLq8IzCrgkGVmp4mTOB8glQdyHvd8doy6pM8opUuZB+7CWTdtzNBIW9pcR7065/eUj/HmMv+Oil/ogttCagcyv8smxN3xzy7xXZoB776XsxW+yCnJeXf2ysc60FMWZBsyFHtc4icM0FUJLW4/pdZ8ZfxzGSmxRKSOiAfxCN3j92dnPFx6IeUBlQprXXuara3YStjEfZNSK3TDcYAvYeLZoLEccTFGOPXXN94Jf6EaL7L+ZBNLxOrypoW9eIQN6OJjbbIKEc7YMaOtU3HecIOeVZLfB66AH+Vljtlf+WrzECGu+oBtAJLLBOYQbBE7niibxeXBPTmVgxCMQMvLH8FJd5aKuL49CSZVu1gnG7G75P2nRI/y9F+w82+rcaC08M7/EKmdUG6k3+CGCp2U8786o1HEaWelsQV4nHL2bjWcfiMt5/lQqbtyncNwL7j4b/DzJCSPJjC0p6Ot2/MBAWcvw+tkhRRmW/OhVlowsYFRirlIC31ArLCmiBJLMsfzEtfjfRiMPZz0DTVmw+Hc2LLtQ+9PsosynmkhhGXA7DoA0iKIS7ZFmIDYCOYfi64Ug=
  - secure: WYa9jQjDOLsvWYsUJqwX9LrJ3yM0nJb2xsm4HO8vrrkYTpDZix+NNGHOeq9uyDC+9z1vhEbel2LHdcFV6S0ZGOrZN/P6psq0gu7kBTI3pzF+7nsVTw7q0MNZiewPIKXxIGJkJc+InGJrInmXSnEfayoykN0Cmu9RiNHRSOX7sxuj7BQQHotFyF3jCrCbAK20VXVpQseIsmwemh9ink8lAdLIB6IP0qYWNCcjYDNzW57rDxbtZ9t2IY/0FESoQiiqZrIS8QSr1CMp8JQJzTyB6dm+dMceyKhJT7hUJx1U42lgPFvXq72/srIykJ54Ad4PfoD3wceSYQq6kTHwV3TAfeeCil54edO8SaicsPVyCvRDBG2/nWP1yFbKAl0Ll9TyLZHl2WnwWMOfnvgriRYVK+kXY7Y9t9FPhgwgzaxx2HrsrXTQe8qVDd5TUwUeZzHprEAOPXNSwb1db2RJ1nNh7aW/QOqAIi2msZzUTkKTphMP1jrun5xQNfS5jNGL8Z/2m3PhrjPs/dqYWf6mK7tqBz/N/I36QHMZlaV6h5WGZOFxHxY2DS4kELvHu79fAV4p1DDDAmVOBIrmfMdz3JMdZTfy26gjVO2bXI0CQoNAG42Wjeg4pFDouM6ZYq6niGi5SdDkwEuRV3N7RdzT+smcbd3Dfy3ENASktqxqcAcObpg=
