language: node_js
node_js:
- '8'
- '10'
- '11'

cache: 'npm'

install:
- npm install
- npm install -g gulp

script:
- npm run bootstrap-deps
- npm run build
- npm run test:ci
- npm run test:lint
- npm run test:sonar

services:
- mongodb