language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: vTP1LoVnYMy2jLRGjYzTaPRDO0J7P5ZQAY8OBedMEvuZYg1K55nX9xFwIh3vNeXvs/e6hQy3227AmzTbxWBWsVprUXECaDjkBeVCeHwf23jcXH7piCekcr+mj7Qjvk7s2EFyuitqNbip3ZXzYTweT2BLpfQLumosD313XKTjasHQAsB21t3M5DHa+NO5qJqdqOl3YceKvPfbkuSi7dF1Njs7dGbY2zKWYakw+tNtkvialmwMmQuutT29UFedSpE126mofnOiUEBQqX5lctP9KbdSfSCxfHClWWkMBFO4KcMfNXgZa/pGwW/2JCJRrWVPnF1+1j1oRlKbWM27pmELd1TYT6BHGUFaLExpsKF9Jcmd7qa5UcGTOgXnT67uaIl2svWShqB9btA/sdcuzRQxxJ0GBqO/mz8WqzAhmXbchkMU48mbfr7HIze1F8Vs+1ArnzGJ41m/wgILkVIQyoGFIqakP5Kyu9CZkWw9QYy9hOhnDCoxkg1e99IJHxX0DDyakOeE/LEF8+8PHxn+L6dnHLOeK7HwMjeadQg0+5UzMcaMzn3l0Xj4Dv7aygeOuDgmSy1W6OUAsNq960tHnFuoNSSB5mnpG8g07fxgNgJbOfaC2TrwEvI9irL55UzK3PRqnCNXrPTs95jr6PhNLP2+kp4Yw2At+4hYFKXkU7KCoa4=
  - secure: ufNu9vpaOUhbNxkwX1afvkgeftI8KA+hfxM+/71nSU3Hp/IlyPr2PQruahI9IJa+WkxKqZG9C9E+cqPiZIJAImIyvwdYxYCuhh++4SAhS6pzb5FQJH2huHWKSmuoTUrLK5oGYHiaPd9rg51+Z3DpEWV45oT7/EfI8HiIUKhKtKNheRyo9PhVD6MT2hhI08FaGVu0iK0ZKu/s+aNIRpMfaHUdEa+cQDTGT5GFlx5KWBugNosH27sf++65LxaO81W9nyWYMTZl+L7omVfnJ2BQq41MCVBhNA1l34swDyX/x3pxSvL0kRbKSQCMCmzb6ejmDcCN44PnUoRORJ0DH3b7ZaeDuM/qyhe+9fTUFv4tx+whwu6U7eTWxnWz6w06EWZJZURXThS9GOg6xNS16L8hZg9IQE+j8GDW2TO+nunNeACmkjEmreoUREgSIWhiRNLhX0Rauq4rdVB62R1UwWXkFxCcoOm9Wqd7iYoulErWNyZJO8hD6VeqN6TV9Gz9LqVTQ5Mz2vD3b+BwTJ+Msxgx9yiC556gjCyT9/9CwLWId/oQTtbiW6E9KafT5uPOcl/sl60z8nNYNP4Ozx6STivmOKIsrVSVRuG4QevasuJAanF+EcGh/WQyC08pgQ756KTIygdzX6t6riynCqGAMD1qPCJsKhcNaqPyrcLpCFt8W+A=
  - secure: jWmH1fdTz46yaB7Bsa9tSAbKUKUuuaZF46q6L7PiY5SzpImSatdnINIbLclVd/UdOH3CczSOOuBKiXHIFESacuHURMl6EOxicKfJ9TcIcZw5OM3HNWbRPZQ2Lylxh8LGykIyFE1fqJQN40sFzIdT7adt+RYosNlrwbb11EnntOj1/uros4fjD22OPD1Wu9hosBChU3h2NcT2e+G2Vj9x3Q07AvnzSivjj56owXqgfaFjTJx3O9lGpsDyIvKMtbNQFm7cPcDo0hvPLSEsbazldFuZTO/6O8tldjUOT9omHYiSFPVS7Cyc8pfgVOrBNdS3c97cOAvhwaOnOYT31PXxUQZrIxNMthFnCrBboHz97InEhd8GvDRvstv18FvzITGVADvIQMaAe0cpzpBb3A/+IKYqqqSduPGZ4Mv7aaZEhNG9CR2TR3zmay1uqYu9C1F3Gqdsrq+Lz17XyfiLRTvgKS24Gs5goN4FOoB0GbWwzbC15sXoLY2BT/HpCgAbpjmuPvPLe9ittlLOe0hF1sMiyk05SvIhcfQem8sJVxclLR/z5xTzIn+QGSPobgQhi5TqXDAAYTNq1tWjOM9JfzJ/HPxyttQSLm37Y+o/nmMRF7HM536uN4ZCUmpFhPN87pSwAyo2QBVf/IS9oJjfFXBsd4G5NVdOLyOHnSa/PsN5PEs=
  - secure: dju5L1Jq0XOHH6qlun7tMIyz/bH2a5hiwipMUrPNckocn7yR9TKKqUivoSh/jyJwE6Yunc77tAgrE+VyP+90mAn1mKOhXM4CkrYH8z00uP4dlfYBwYt73E3lEQiwx4uNYntEMIWe1QFxrJO5AtOwuRyZzMTKWnUPOI1iWeDAP7JSNzxCaYcbugTQ3eLFeTijdUJAqlIYMthdjCjk+HQUaPcn3NenZAPoIgJw8WFIp4s+QzcgqBgvMck65IG36eTmhXlNtU5XSsiUC5Vz/94kcmmq3TvVHW7PW+lDrvcm39bH9+fNfASWEBxwwxDgmL57jeicsps0S1844YYoGuR0Ub1PABR/cU2iAhICwtRl2qfdRBhb/kXp7DYSS3YykPWBlonTmaQY9+xfPZk2uzqmMa4wiZdjO0qi1+kHM76+4ZsXGrH13u/7uIxmBkRI/zMI4RikxMJEeEzoIpl5+RpDM56K822QNs1+k3SMZJMeMfQfvD+F0BJnZf06PybvRy/tAG9QGZgZbjvQQBTI0vVvNjjdGhvsdCVXVP6gLrPQldOgysWFiSDAxQZ++2mrx83/98A9zCFGKu5HxHGDTm5k40ehI43BKc43sJ6MYwdz3FvzOenj25CyYZzteOCAhOdHtDX7ID5RVgVIvQM51nos9Biy38JHWyNPm6PbNyaIWHE=
