language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
    secure: RvYCPDS5NQKVZgPw+o96+aehbCDoRw5OQY39+HVy90k9iFtAJOTO1qvcSun8hmhCIN08FPeiIdqcxZ45nTJVKeQwgIhwFEn3bXN725OEusbGuGCa97qn0fTLv/J/V6zlQrSzWXUwUGTFPZAYWGSxokaJaq307pgNO8OwlC3r//NYt0X8H5K5YyI3E+al6kHWSTonwsfLakex/IETFaiLaA2ktmYY2PZaSdUucbOw8zwu2wmraHPJrdloJRBhyF2ywxkPckDw2A/wwl7+VvdZAADJUAXP+/rMS3M0IynjT2C5+4D/4R83Iwx0T9md9wF1YMQUNydl46iwl/J0UQZ1r7fZX1m9eHXA+HnykaX+ClAMF8frBrQ8yYT1ThQkMxTtDhw0ElTTdXP9Uk14Ito/ofIwesX1nqxByoM1utB8lXm4d9MS3YJ72HbR44auJrJYW7dN8fTAXuxOXQJJcbPRAqMSgYOmuxRJUBNMi85THZfLphW/GZVBsovfDKaw673mYIDw6W6zPPC76CJ0mDkmS+at/zN2dYr765QViDL98UDSkwAFBRC/ehgsJUg733x3NbjNvABOVhVRHTWN8DMlwxY7lRx0aYaF0glq5/NL1mKjNBu+bhiB/3ZKAb+zPMz7URy/w+uJvM9iP+uEVYFdTfP6vmDDIq3avIKJWTmgAnA=
