language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: ZEJX70DblheDcLEqEvFWhjHFPvmDWrlHziLB06OSiksPt6GxVW7EumUb9/2DrWp7c8Dm1jt+97Si0Kw/gSt4g6forB8cNLMfuucoWM/TXuj9RfvInCnOMSYVpGN8aWgY1JS5Q2A1cY6r4PRaFSrMVN2y40AWbw0neU8rnjdruwWE3ccqKx/f85az6V9SmgxbSMXMuOdgAOQZKv+sf9qf3/sDzAArGoQEEqJ02GBpG9KucWFdb5+3J/1LKtxf1NCWIR1RbVp/dqyZVp2bonebmMo7v1yffk5IF0EmRIH0cuDqkUPt0qlJ7aVlnU4DAG+TJ4SjPkJaEbmUZU286hWDT7nKuEh6KZZa06DIaQDZz7/lPGSKLMp+tofARgPEXSmU90ux/sRGlWECIYALtELjJEtEudqkKdXAR4IQJAzuXQw9EnDL42/Yq0YMRVa2AXTeh01UnddnnCPiflC4L5Zt+WRRku7DRYWGKnf4jebfT3gD1bVluYWIW2DIfTQr/SnjCAyn7at7IHySmX1yckLhQBdY3vqi/LQTEruwaa56v4fCQ+MslULx0oJV+zDuYj0yEjjfMvGtQCfNTItalr0YCK0bUtnCerjRCvvtIDi1MnQxIVQ29SpahB9rCe4Oj/G40hlXZmE+SIlZp6i4elvngLkMqjSKeVfrf/pKrL8D3Xk=
  - secure: EklLnWQmv46gchtHITnqp0iZlEqm1iTupDn1QbIH092EJQLLDZQDwdd8ezoub7CmimxPoPi0EfIfjPxeLsFUXJPGhGxwvIA/J2lPtb9nL1JcEPUoRL5gDK/qYOQpwcbcWggXTBsls+Bg/0SbpqXCQyRnj64xxyRkbCUEdIo1gfWhTfIpV44ij03ggRnpKezXJuRCRFVQ4Eq3ea/V+pFxT2ebqdKurA2qr8U6jzZHzLaKqjX/GoFFGzNlTe0Nr7Mvc8LToVp5I+OPVDt9dTJWHq8kvUnLZkWJVQ/FkTf4MBeEOLesLnFFM1ywHt32+kaT2+FwCtYhOKPPZGhDT7oeS/xyiEMZYG0waXGB9gu5rjMonDAYTdLsTs1w/7TdXXOfi9UOwEATQiGTdj0PQFt0HbsB4YZMlncLGyCUZfNKVMATl5bmNNY+o8boQEjP4MdM66ym4fsXAeNVLDuAK93pF7ZeLWgG1DfsNyrVUhtUgyxy6PF0YRv5Hm2Vw4c766eSd/W3isvH4mVHWyn0qQc7yWYx7pSTTATD1edJkR7Gn5c0nmYJ6pmFZgNtEST9lnTnjdGUKFWWoOO7KlXc4+Uhvbgy5ArcubgGLny0Z+OG1FapvreAkx/DhmkBIDiu0/FCDaDhLOW0SRFTRcK4fS6LCf5d8zj6KDNeI53luqdnpiM=
  - secure: oMNWVibVt3hBamLTmGiYPfqJkjjw8wYgNBX1VpbTsX9KW5QLtVX5dy1y9qnBIhu+coAwyDUY/8sSi5UNFkrIwGlS2rXsAa6b/sO6PlMFybsP1Ebfkr/+7ctlW2a9mqUjIO/16w4p+zuhOzarGMss+rRP/pH1wtEKUdLJRu75YuiOfFA8W+7RnOGX43OFP5Y+04c2KSi/VxnsWIjLTKdYV6OSSimZklDMeBfDIydBvGVmQS7F2Rj/QSFfua15/UnhnLG4YfuDuFZs0+NBRhfxhTXXlil5YQHy3NgPI0YGsmY8/3kdnknXIaJGwSTf3YV9HYskv/RBbiDHlvYGhxG2T6ShASh0xlFbkujrXwo9yF8D+W+PGqDGNqJqwPq+PsHCAtzCO9j6gQZpJcBpvgagqynuEgXKhJhpCe1lnY9U9/nno5SRDkG5MjKYlQCXRtL8dtpuyxXWltWZ1+m38ph9XXbdScadpfjLUI9kMRRdf5EBtrhgXsxH79SJE81Ex709oThmEwlT1cYm93LzHwsHfFIXcFLp2Af/+e4PdGiMGjxViK+qmqv37GkSw7BUWLUfrBjxRQK20izDrSV/Pu1Dzmkz8Vf5UCtcvslpfve3KifqPS5ZmG6TqwS1Ub+3drRtMa+DHhjEGVxrCdj+1asmf6Qs28edHjHiE+feGanvXRk=
  - secure: 0fyR4xEgpRwejBwGb4O3frbo42NCUtnBEhEGbTqmZwGPPgPNFQ87YvEmtJXl3WIJpOF5JQ5FPKmn92QtQ2sdaoFu39RBBtt+kQRoModHdkafuhzIaGTZ+y3Z22U5CV99ZeYmN8SVnaXRvN1SP7XPiOMGpW/V6rO0oLYWgIjL4uEOuDcHZajS37D5Ydi8XE0V1wLkxYcFSYAgF1d44qDLmoTbzZEGdf2mNYZhq0TrqqU8v1WbbSgGPf4vtOgBxaDP8+Rwe6ek/UQT97v5Q6efrk3OgxqSnnWjIbZiQqOSSHBYfbxkuzKBCo1mUOZH9nZb/bNR9qPPa+6c2vNNPA6iq59et38IbkE+MBRZpOky+/PZE+OSEvVKjljWUJqr6sB6H0QENPjfLY7l/6a/FK02Uhidtl3WqpYPu4a5RsQNfqwdqabDB2LwqFMLlrXvsn1tcaDPFwOxoe2CguFO2Jmv1gy+Qk6oyrUgZ6wwDkEoxi93pYrrZO6dToIyxWqgO/Y+Fuye7bTxftsg2ORCAQa5OcYVQfLvGNa64kadXh7EzhKJV8caYu592lTA8GmkMdlC2l727ozEpeI9UladvULXQiZi0Lp/frlZrKNcBE2SUa6thUkS1mGnWy3hbWDfaJ8cd08nyj8DmNlSeQ0Rb3UkitFiPQxtTjZcQ52ycnlWKaU=
