language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: MuFhBbH0C5wZCX+D3btBRJfDTpwbHAeGVUnO90uA79RirJtlgY0FAGEZhDN2SWNw2WIrWAPqjXbjgwHca1AJRTfA2RdkopUMw9LYczTGHj6HFDOPozt3WfKoy0GDgL+3V2kaKFX3sc9eOG2tqy1wEaj4wmHNT13TvCmrzwN8SYz1cy1reLvPyteTHdOrWA1Jk/amEe9AavWmHpxVMdLPfUJKhR3zxPwiAmx7CWXjKnl/kxDqg+3AiSo6KTmnMPvuqRZIROCiYJhcmSQ/kwXgwDkOW77Sp576YXxFWs6NNrMOtFuZcidxoDcJy3uUCaDtNiTC13towmXmuOBxcQmwlLaoIMLR9rvos9KDKYuN/eW9iyjuzMJ7Fu/EOnxryGaz9DiJ0j8W6KsUly3l/JJLrrTo2bHhmfdXrSu/jn6Fg7fVnOx/exI1mdBqTNOHicn/PjRhYSzEERXaF4Wbi5lpJzbNTibQr2DHK+jouX/gRqhhHzGbWRtP7brCXaNKc5w4J3S4yJ3mTRAoGa0UYWlrIFl8dOftgDVXrljt5eNT8vrd3O5Fy6YmAngS2f4HMWCSfsaE0f+VCJo535xdDqZ5YDK6ih/sxcRPBBRXBHy77GRL1POXFLG+XFCQri2PEc2FdFZc/uUsIoyqu0bjQrTMQuU8SiTQHjHvx2grG9b6ems=
  - secure: JdCspNf3FMlQLABS4WhntrzypEYvUlXsQZ6xtsXBfLg54lgHy3RrreTojArGcKrxY7rOKqJxQjRli493lCHS3BV2GMeoIf+FskBVa8gc36GLNjtSqgrxyTOhN22TR+MY8uIq2nOJA+hLCD97xsUjR0enO4KnwCX4LDAo2jjHkHhm3Qc/Y8saaBC1R8ufWrr7BJoNSb33TaW0LuW042Iess0YNWUIjrlvrSZCw6LoEpPu2qUjKpzDVswZufF6hqA6o+SsbNvD4xmbT2ky4eJF0O4E167c0MM0EPaXujSg53WalM5ncINMtJAvoWF19c6XADUbdryLmbX8VX3op6zz3GCLbukzZrHONJ1Fnck0BoI2h+ytGTp/6SiYVDi/YF3ZcnXJMJO/iSdF5Z8TkZKORE2UYKdnDyj/ygVZ0cG9i7a+ZnLHpG81jYg95xiH82gfg9mEdTex2RuUyceNoar4Hqb/RQqQ4OYhq3YPxIQP2IsTlNB92KDEwC0Jvsq2IR6oPGXg2MhnXVur9T0wcBxCawwQ1dCT+cUu2pYCJRualgl8cbJmxN7A0luLFjVjBiNiymlenVdlWghurqngvpqybutqnyBJ5mciMdO8q3kYsZHJ8GGFiwCyxJHSojjAf4Pi/0XUeQaI2ypIFJUjPEwFzp6MPinrhju3Vvkvf2k3arQ=
  - secure: FXsPDX53Gp/Vg9YBQi96KSHcG/BlDpGdGoUDPLJilhfj3ZS8uDCV/IxbV3+dyjh1g7ItS22OklTcb6bNiJ1WD0secM4/84Bh05Y9I571Tuc3b2FdC60fqwo67okTM85p/KP/jLblGp5WXY6uCJ+8wjyqcPZfRNWvrj0Mk4gU3twO38/1QpblQqyTG9iWq7xunUWYJRrc3MwTF0ryL+7VjP+dUfYwfy0OV6hzeCACsrYPnKt7I8OTH4pxuThWNNQQzCitJ0oJdvEEjQ5yrAqSDgE46ADkT0TqynEWnOBC4agboub1Fku9tRnht3C5L1P/l+g5nDuAAp6iqWvqZhX7sqVsJFh7ytK/cMoRSW0a9QsGkC66iYbal1YkgLBL89DXO2sUFlQwqR0Tfz/TtfIKcNpNsXUXTUnL7TggVmTrQ4c+9fThlAdhGxFuvLI+GpcxA3GCY187ebu5rLZxGkwHrOFAMgIBFkRAJUoazij7SpwLJ8Zdi7ffoL3HxHOyGioDmkVREo/1atxMEYOE+SET7BMVbzw1hJ+xM5mR7xUzreTtCO0wWv+PMOPRtX8VUV8ylLoveWsrdfwSUmTM42WH7PKIMHKfn0rFdZ1DTV5cPbSLKQSsmxScaB1KOG6XfXPRiZPlLDgxkxosG2pqG1V52SdOunlnWdQkE/u1FiKW5uM=
  - secure: KGlmIdF/2KplVeaMf6JI86EbI/IENNw8JXUJSHzViRV5zP8LH4llyMozPkaDX/AR0GW3KsNS4zJ1bk0MHB6Yz6fMt4Ia4sXWR10bKtZy0oriMLLdR1OFSAm2p9zo/Q1NfHRTeIS1GKPPyOVoCZvWCeDDnXbvIKH6pPoN6P0IARxaO3LatBx06Y7LZRHVmooZ/MornHRzCUZvsXYDyQYwr1eBGi2yzdOxC4+NcJXLTxsmrwgJXRZu02G5bRaSwi9KLN6hlRjCs8JGfzuP7TS75iVbmqxE1o627NfFm/EbFU2gBt31EJdDTw+UD6BY7paFEeAprMzzDWwnOJMw/ju4VvLgXrrIcRXLcCtJb9oAffdIjlSPNKbnPpxXCQuj+xba4wwFpc2sHmqMdc1A2U/uP6PxXhaFJNEOUlHnIu74ABmvQKoItxumrHAhMnyIiBmozQO1evaR6Pn/s3bvKvrleRNnUJyqATqTBMCx8M5WTNJt/44ZleaCSxeM8Qd22xh1yj8BulNQNujTNAfuj0mNskJWPk3dX80eAeftRMp3fZc59kWC8CewFOHIMGjMnM/Jlwc7vmvVYPHi0wkgkAdkYUsN5uvFXmWly1NV+iObGQunsJ7907OKGcMWkwsdCOwRMXEh0L2cokdYNn5sbq/Q6oJt0KlNx8RVegqnqxDs+Q8=
