language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: X1HsfwyYBnKcK6h+QbmhwQMLygcwRy64EojMXggDT51OfRVEAXaFf1CVCGNokgnci3la2sUpGCtuN/IhjFzp1+3xaECrhFxn9/qicFH1rRXq+A10Pz1i08PQZZ87Q9qJLjPiImmCPGR5kMIACdpanKKLl4b7wwv/k+O0OaD1jJVRH7hq2/nMMkgeCmA13s3YvUlTOrNRdYfpFwvJGx8XZalKTKHmL0NyUE9mdaID/uFnZuJYUgmBp+oePC+TLC3kUPA4cQj3bR8DVpqTUL/qqTGwNf4s5PHbgsxdwC+TeZd6ECZJx3z/x6HwI3XRDFHS/idXLgRl53d7dPGDqsSceD7QBU9JUkzOcmy8qLh0iFV6c4v2eOk3J3YxQy+B3Lnl90jdqIvLZdAZiEoNpv8lXGHx4qbZra+M0Ql1PN3b6usPq626JCRA30jCYElwtSA4FvhJiCxoCYGhsqpHOJ1y/ED1XJCnvgD58cZFoLN0Mf51arVJvd1X+BU5dX61jTH+m17jWORwYjE2bZtRdpK/SuewpoPj/Mf8rPTX1YuHGWfr6YIXImZoWcqDhFCjBSV0XNviO9jkGTtD5POakp45rZl2M1I0pMMPWbnABQooxLI6eN8iwt2dJvYJwwHPmdX7HFnaPiyIIr0HupzPmn4EvPT96Yr0cHig8b+ZZzLUqww=
  - secure: LnH2JQDw1G9eWe6JHbZzLWBJNOwEXamD7qKBx7Bfk8HbdwMDD4ygkRNCZEu5ZVQvRSTSDQ1K+So/pEzWU4vU7uW/6JC/XSA0ewWLiU2kM2/9Skx6rIoZ3/vu8LNxD0GL4Mr0dPXBeV3aN4nnjpklhBv1TcAJEPaGextVosHRuZ8ifpdq/i+BJ/XKOOX6qkJL8cNHGoM0L6xwZjsBL4grlkzAMOuG75pypEYq1TC+twWq6BgY7pK4V2nY/+Go44XHspWIH0Q4PIwl/bceXlWytoM5ns9fzBTnQBhLCo8MNfZfUmiRe9hcMmrHtTicurV+dRAbYN+MOQLhE8bQ7tLBw/zlyrzKeMCSdWMMB+AYhBlGpc/ZSUpejlcbr+07eE7wy6jsWMM6/t9GZ/mdgl1YuL7rP7Kx34luK1aPGowZxIAy2DEE6mOIN+l8uGcxd5Y0lzuvQQLCpRr/9RASCohpaRXzAHWC1dvnvc2/povMROww9cVZX0T11X1FIIjVqVwUOTwkT6ByOUFJhrrp6pl/Nr8m9oLRvfac3uQYX9y3BjMq3fb8lbTxt5MNtrZjlYekZsRj0oYSoCRVD01IHxd0/lnuijptm5Inwm4Qph6iX3mAgXA+wLEb+VJ2lHbHE8AeHDRkzy31kdAIwqU/utu+GZMJZxlQihYdaKvm1Onoz2M=
  - secure: zqjNDC4Ab/T7o5iMP5bTBwyXvclRRk1YlrcUZr2X7CWvZqtdf39wrd3+Ii8R9Akgl4hohlH2HYFUgQ9CBxhUQhQ1ANO0SyIEFcvaevOVMomT25Z0KTJholG2CsScbJMW0UlMone/qCbTpd+xyIr6hYY1B/F1haM4gedu6lfOQ3l25Vi2GO0Hp9DmlW7ttzucrk0kF/gjYl0VMlr5TyFDNsp11TWfYy6Y3ppk/WRKGKb75CXMosH0eM2VQ9/GwfmrQVTxWLPqaAYkIOAqSZFgVtYlipru0BKFOvKnv3JFG5kLw5Pf9E1uK9Yo5jZW4pIB/6fhzSlOsAYSNbwhZvRDbhr/NcjaKnsSa6QUydupera9YD32vG7SDz2RbrpsjS5uMvNDmox9qb4+/e6nF7rM1KQagYGzbgv/AY3vgFfKSqDBh8I0CVC9drcgHk7rcWmd01Qs5iGi27o31HtfL/V2DlcvACSUNPWbqH2ZI12SXrJyv+9kcV6YXyFcjeCh3WVYDqxYW7ykaVzyhgxsabQP9nJckjc7SZI+n2auCwKUbUiSouaVmIbHu16V8xRGwHNa3sC6asHpPuLmVxhA/BPloKHYEMyzSPrbcRcSYMEN5lk7Yi42BIWFgaJOqSrYA3xS1NzDDCTCn5vTrdAN7RiiJM6KoOfeyJ828rH2n/5fhv8=
  - secure: NZXEcW4DJ4HnoiBLUaJMy2sB62g9a9POQ00LHJkpAfXGPcgsyOOcd53PuyVJldnqwfI+Ds1XWi6gVgHe5XLoUI2k4qSzWcEd8hVN2sLB3n4SOKBzQFc9eh9iSg4r8KBfhUc9eEwUowqi5jacLVaLV2zgVKvrrf27LwA1kk+N/QUHMjn9ZFH/yZrhMeprluqt7PR2V2wDvlQY4+08NfnSjSepW3KqHHR7sBz6QQRPi6BYNvPToz+TE9yEDlBbbqe81t2Yq5tGdkSeRhVZ6yBqy7YTDkIx0AkfUhfYH7HR4VCn/Gze0cJjWekz2Zm/QDGPJsd3vGC0S1wvjxc5BX/TZFB9H1t5sx8X/yAuxTM5mk1sjZxTHQ/0NbzRnPVRwL5ceqKKgAjpeRnsaS+ymI8gT8QonWxAfDAHTx7o3OmXE5R6zZ4pXiRw60rbf2KunERNgUUVvbkZ+KTYSUYmq1TakUXQgKf744fHuUyHzJ7NqouthVxydBKmb8EP6rxoxOxXNAIMnUfUn4m6KGRPE0r8WEVR6gSli10XEiM9YagEAlB/a5M7pJvd68TEsvvQjoZBOxllm6gvbGit3zAynunsryPr4uAcUroFgXsEUtnr5ErvyY88Cxn1IMhM0S461iHdHH2R+zfpysv0iWwXJJKYbX6XLr1Yz3fYuwQeFK2GsKE=
