language: node_js
node_js:
- '8'
os:
- linux
cache: npm
install:
- npm install
- npm install -g gulp
- npm run bootstrap-deps
- npm run build
jobs:
  include:
  - stage: release-alpha
    if: branch != master
    script: "./bin/release-patch.sh"
  - stage: release-patch
    if: branch = master
    script: "./bin/release.sh"
services:
- mongodb
env:
  global:
  - secure: "J0nlHMTLX31833QlX3Y4rr4HBEl9WYmmU1j6DyAXAotue7rGjSziwTNbTQwUbUMYYoSeO3H3/Dv8XI2IK751foyle6WWv6xXx3TzgXroOaUq/kjbTARtB+owQ6SYnKJ6F9YeEv+D1DbFRS5I8dsCmOYG7tt6eXLg52WEGCWGnG+VRCWVBJB/XGVkh0DYbjQ66o10hCZclWBOo4T1HqtbY0lxejBkCWNJepanwNEp+v/sqdNR/0lS2Rh1YNB+yQGUmEVYVRoSuyhXfYIQ44A62LF/qsDhc3ZT8KcKbk6x+sF8Px0rf2Q5RFo3w4TRprK17QBL1hRwKpKv+MzMF1cwS1p51FHlpd8vnz+Vbf4iHMqECnShxt6tqZGnmqSGx57KnHYZq8cgHUJM48hhF9qmrgSoyPjYWgGdlB3bZPiBPmS66tcHgiHTDx5gg4elrtbr5gy8teg+QEz9OVsq0svJlQXg9k1f6fYi+kNFC2dXkfp715gYDxdIinlL2w/Wx9z5HTVLNNSLFM5/kz7e11odnFA8qehYB71wjpwDA5HB0g+O8tuLUye8Gm2YoMrXQ+hKO8x8sKFZNkJW6JSqTMGD8cX6ofqW6mf+LvJW6aCXJ91WWrg4yg68zOI9ZKRWAtL3ZAKQ3KG5+gc6Igzlm0A+93qRYQkVO/hBXMoiZ2NvxIc="
  - secure: "Oe1QPESY+7ANegRMvPJ5qTBfWJ2HVlULICw1Rxdd+ao8aH+E7bN41ofoy72N9Nw920BADAu9NXbdAA4LfFbeeCtHRpmSUolM7ffUJbWOEJxoUEGB24SZ1H5U41ojTCqeDa4N4yzdMmsJ3WTDsNgAN26N8QbfptjQ7i6VBVVWQyp0A9s/265nYjQfI8wRz2oX3rmrw2vd1iUvwcN/pDITyu9AVG5CPTyQP8GUFE6HQIbjnaL13okaA9qHoOFYp2K2ieYPSFevJp54K/fjNhcn+eatBP52oSvfYIYqPMzJPKl2Qew2aWNtgaRRKlwQQvSfOKDuA1KD07hEvkGhIxHk12k3k2YKRWhxpV2YrSwRam8q9/Y/pNhwg2inWWdKqwpgYnYWsjATcva1Kd3psNxrfavEfmc2R8qSJxUGyyiC+6l+NQ7eS8PVs40esFEtkXpNcprEuvC5KSl5cgxAcRSGw7I9Yrr65w1Xv36x2/USbFgT7hMbOqru+0YZALPKHzAVyYyZe7/HFUQd6w26dshvfFc1Cwi2BqPlBAKtyrKFRsjkHNFszffQKkJtX1v1W730PcQRvF2Xv7m0IxDHflqQpYBfAjZqUxXReg/SyT4IE3XfRGMkF2r+daW97xqTXCfxSJFNFt9165srjB/S4G4MFP5VzOv4K00C3xFBAKLsTgg="
  - secure: "LhjrrbthRrhN+9d2pJyN82Xn3BOgjDQGnsCw/FpYcUVraL08bYadAqm4F40utHTf5AxqidC8R4OzkcFGLoOLDnh736+cHpKCKqERndFT18b7hDKcNhgbxCJuDm8kmJSpm9bhD/KhbXksmNlaRu6Wo8A8RqBMGe4T7t83loGTilD+n0MLzgXcmdq8TcvwmaUbKqj89SCnmJtyKiq3wafO+OmwEPuPXZ7xhQknsssVZN7H33B5SbiTlgVYmpu5+83nIX8Leb/hAyB6Cre1M++TeNKP/v/yuWeX+Ij+jM3hxLUAvvi27sKl75aLE82jhwcIulnxca0jyT9DVQ6ARxToxutYqzIUsrjFyDPmPnN+eKlJ2knxKEAOREZBdDW6KbCrLZSS2lWgPirv4YFjHNe3HTg/xq8P25C3bNkTJyD3w4CVqd3di7No6qRMWT+NX3iYUrZKSDQBjjI/bYDaF6tretuTVvvCn3rCcmv6eI0ShX2dGyE+nLts4LgD+xW06/U+3iEc7LFziOkB2sxn0toU1IY9TbckI2Q5ps5fBaPmrjVQ4YqYtHk81mN3JdRQn6MDfZAGjKzk7aQrWKEEsJXNH9z+ijOOvKS0/T8LfdyBRsr4Zsbxy+NFBg31M96hC/i3VcCYI03EQz+uoXnLqRjVeKdIgvCYznZsyyzYQODaGq4="
  - secure: "wD70fTAUrqxeuj5wypksM+umRdi7gOrMITrQ54MYwz8kgJuwrqNyWk+8DzQ+SC0n9WzrSHItitTpiI6hYD0OSMzOWWcEQ7D02kWEdpawLxkC7fVYtwAvzLbN4kI3lGT29IYoxLDcQrkGK05Eypt8dSRAREvj3EvUB+PX4WRJYpBShfcedOXr6RwjJBVZ5V/Y+sigQw5RD4hcZ3EdKnMvBgz97oTflXrnDF5C8YMgPg7Ao88VsUbYl1Pz9RZ7b2GDOvNs4DKrJndelBECau5d0WCyQLjRAcI/aWtNZTYsTV4sXZuukVcraMDRE0JsStil6NatNfO4KQHiFlzJB7ew277YkEIlQ1NCCZvZdOyIwYLbELUvpSPqPx2u4ZqL0qFLicjcns+3724VKYZnNIxHKHvSutgUU0OXJZhPD5YIKZpRH5UpPbOXcqFEY3IHJoZP0CQkg7+UwWKZLb7S7xZm0Ap/QjLz9vOyEQ3305ogqJtNFctubyzxIdyv3sVAW2fELJwK2GY7kI0qwgleGOPuBvwgfBumsaRgiOekzEjlSg43Lw/ldHl/BGRI95zm1i9WkZVceOpQJLqkYtgO6dZqv2J/sEjx3qk/KuZ8urMFPKJH6sAcVzM9UzJjZCzINv453SIPegea8zYtJnp32bHgQuQVkpYYTCN2MCx+K44IvWQ="
