language: node_js
node_js:
- '8'
- '10'
- '11'

cache: 'npm'

jobs:
  include:
  - stage: prepare
    script:
      - npm install
      - npm run bootstrap-deps
      - npm run build
  - stage: test
    script:
        - npm run test:ci
        - npm run test:lint
        - npm run test:sonar