export enum Errors {
    INVALID_NETWORK = 'INVALID_NETWORK',
    WALLET_DATA_REQUIRED = 'WALLET_DATA_REQUIRED',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    CAN_NOT_UPDATE_TRANSPORT = 'CAN_NOT_UPDATE_TRANSPORT',
    MASTER_PUBLIC_KEY_REQUIRED = 'MASTER_PUBLIC_KEY_REQUIRED',
    PROVIDER_URL_REQUIRED = 'PROVIDER_URL_REQUIRED',
    UNKNOWN_BITCOIN_FORMAT = 'UNKNOWN_BITCOIN_FORMAT'
}
