export enum Errors {
    USERID_IS_NULL = 'USERID_IS_NULL',
    WRONG_NETWORK = 'WRONG_NETWORK',
    PROJECT_ID_IS_INVALID = 'PROJECT_ID_IS_INVALID',
    CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
    JWT_SECRET_IS_MISSED = 'JWT_SECRET_IS_MISSED',
    UNKNOWN_TOKEN_STRATEGY = 'UNKNOWN_TOKEN_STRATEGY',
    OUTDATED_TOKEN_DATA = 'OUTDATED_TOKEN_DATA',
    PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
}
