# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:carbon

pipelines:
  default:
    - step:
        caches:
          - node
          - sonarcloud
          - node-scanner
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build
          - npm run test:ci
          - npm run test:lint
          - npm run test:sonar
        services: 
          - mongo
    - step:
        name: Deploy beta version
        trigger: manual
        caches:
          - node
          - beta-info
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build
          - npm publish --tag beta
  branches:
    master:
      - step:
          caches:
            - node
            - sonarcloud
            - node-scanner
          script:
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            - npm install
            - npm run build
            - npm run test:ci
            - npm run test:lint
            - npm run test:sonar
            - node make.release.version
            - npm publish
          services: 
            - mongo
definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner
    beta-info: ~/beta
  services: 
    mongo:
      image: mongo
