export enum Errors {
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_BLOCK_NUMBER = 'INVALID_BLOCK_NUMBER',
    BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND',
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    ADDRESS_IS_INVALID = 'ADDRESS_IS_INVALID',
    ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
    INVALID_PROJECT_API_KEY = 'INVALID_PROJECT_API_KEY',
}
