export enum Errors {
    INVALID_BLOCK_NUMBER = 'INVALID_BLOCK_NUMBER',
    BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND',
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
    ADDRESS_IS_INVALID = 'ADDRESS_IS_INVALID',
    UNKNOWN_TRANSPORT_CONNECTION = 'UNKNOWN_TRANSPORT_CONNECTION',
}
